[pytest]
markers =
    api: mark tests as api tests
    ui: mark tests as ui tests
    integration: mark tests as integration tests
    negative: mark tests as negative scenarios
    slow: mark slow-running tests
